version: '3'
services:
  dbos:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_storage_new:/var/lib
        
  wordpressos:
    image: wordpress:5.1.1-php7.3-apache
    links:
      - dbos:mysql
    restart: always
    volumes:
      - wp_storage_new:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: mydb
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
    ports:
      - 8080:80
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 3333:80
    environment:
      PMA_HOST: dbos
      MYSQL_ROOT_PASSWORD: password

      
volumes:
  wp_storage_new:
  mysql_storage_new:
